[package]
name = "price_oracle"
version = "0.1.0"
edition = "2021"
authors = ["Sina <Sina.badboy@gmail.com>"]
description = "A Solana program for fetching token prices using Pyth Network"
license = "MIT"

[dependencies]
solana-program = "1.16.0"
pyth-sdk-solana = "0.4.0"

[lib]

name = "price_oracle"
path = "src/lib.rs"

crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = "s"
